//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4tablo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis1
    {
        public int SiparisNo { get; set; }
        public string SiparisTuru { get; set; }
        public Nullable<int> SiparisAdeti { get; set; }
        public Nullable<int> SiparisFiyati { get; set; }
    }
}
