//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4tablo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun1
    {
        public int UrunNo { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunAdeti { get; set; }
        public Nullable<int> UrunFiyati { get; set; }
        public Nullable<int> UrunKodu { get; set; }
    }
}
